Added EAK's Cookie Bear program (EAK;TS BEAR).
PDP-10/its pull request #2245
Opened 2023-10-18 20:42 UTC by eswenson1

This version actually works.

2023-10-19 06:15 UTC, larsbrinkhoff requested changes
Please add file timestamps.

2023-10-19 06:15 UTC, larsbrinkhoff commented on build/misc.tcl
> +respond "*" "midas eak;ts bear_eak;bear\r"
This is missing a colon.

2023-10-19 06:16 UTC, larsbrinkhoff commented
Suggest adding to the commit comment some description of how to interact with the program.

2023-10-19 18:52 UTC, eswenson1 commented
I've added timestamps and updated the commit log with information on how to invoke BEAR. I also fixed the missing ":" in the TCL script.  @larsbrinkhoff Please let me know when you approve and I can merge.

2023-10-19 20:31 UTC, eswenson1 commented
@larsbrinkhoff This PR still says that there are requested changes that aren't yet resolved.  How do I indicate that I resolved all the issues you brought up?  Or is this something you have to do?

2023-10-20 05:44 UTC, larsbrinkhoff approved these changes
Looks nice now!

2023-10-20 05:45 UTC, larsbrinkhoff commented
I think they are resolved by someone clicking approve.

2023-10-23 10:39 UTC, larsbrinkhoff commented
All good here.

2023-10-23 13:49 UTC, merged