Set SYS;RECORD TIME timestamp for current uptime record.
PDP-10/its pull request #2303
Opened 2024-05-02 11:00 UTC by larsbrinkhoff

The TIME program checks the SYS;RECORD TIME timestamp to see if a new uptime record has been set.  It's not a normal timestamp, but is relative to day 0 of month 0 in year 1900.

Thanks for Heinz-Bernd Eggenstein (@Bikeman) for discovering this.

2024-05-02 13:54 UTC, eswenson1 approved these changes

2024-05-02 17:52 UTC, larsbrinkhoff commented
No, that's not what the timestamp says.  The file timestamp is the uptime counted relative the non-existing date 0/0 in the year 1900.  It's not really a date at all.  It's abusing the file timestamp to record a time value.  The right half hour/minute/second fields are the same as in a regular timestamp, but the left half is just number of days.

Your SYS;RECORD TIME timestamp doesn't make sense as a uptime record.  It's probably just from when the file was copied from tape in 1992, and the original timestamp was lost.

2024-05-02 20:10 UTC, Bikeman requested changes
Is there a typo in the create command? (timer / time)

2024-05-02 20:44 UTC, eswenson1 requested changes
Update the :CREATE command in build.tcl to specify TIME rather than TIMER.

2024-05-02 20:45 UTC, eswenson1 commented
> Is there a typo in the create command? (timer / time)

Yes, good eye!

2024-05-03 09:15 UTC, larsbrinkhoff commented
I didn't remove an r, but I added the missing backslash.

2024-05-03 14:55 UTC, eswenson1 approved these changes

2024-05-04 05:04 UTC, merged