Create troubleshooting.md
PDP-10/its pull request #2324
Opened 2024-08-14 16:07 UTC by oilcan-productions

2024-08-28 00:06 UTC, eswenson1 commented on troubleshooting.md
> +through out the document you will see certain special characters mentioned. They are slightly different depending on your keyboard and terminal
Throughout is one word.

2024-08-28 00:17 UTC, eswenson1 requested changes

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +* `$` means the ALT or ESC key
I think it is dangerous to mention ALT. The ALT key on many keyboards is a modifier key that must be held down while another key is pressed. This is not the same as ESC, which is a key intended to pressed on its own, or optionally with a modifier keys

Suggest removing ALT here as people will try to use it in place of ESC to no effect.

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +* `<escape>` means the ALT or ESC key in EMACS
Same comment regarding ALT as above.

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +* `<control>` means the Control key in EMACS
Not just in emacs. Everywhere on ITS, including DDT.

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +Thanks to eswenson for the intial steps here
Initial is spelled wrong.

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +As you can see above none of the COMSAT processes are running.
The term is “job” on ITS, not “process”.

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +Lets start going through those one by one:
A little weird to say the first sentence here, followed by a colon. Since the second sentence also has a colon.

2024-08-28 00:17 UTC, eswenson1 commented on troubleshooting.md
> +
I recommend you insert my writeup on how to decode those octal IP addresses and convert them to standard octet notation. See recent post to PiDP10 mailing list.

2025-02-09 15:40 UTC, closed without merging

2025-02-09 15:43 UTC, larsbrinkhoff commented
I accidentally deleted this branch, so the pull request was closed.  I restored the branch, but the pull request is still closed.  Please make a new one if you want to keep working on this.

2025-02-10 16:31 UTC, oilcan-productions commented
Hi Lars, I will create a new PR. Work has kept me really busy the last few months but I want to get back to my ITS endeavors soon