In COMSAT, let BUGHST default to local host
PDP-10/its pull request #2336
Opened 2024-09-04 08:31 UTC by bictorv

BUGHST in COMSAT is used as destination for mail to "BUG type recipients" which have no explicit entry in .MAIL.;NAMES. The default is HN$MC, i.e. MC.LCS.MIT.EDU at Chaosnet address 3131 (not in use on the global Chaosnet).

The build process sets BUGHST to the local ITS address, to keep things local. However, if your IP/Chaos address changes, you must remember to patch COMSAT with the new address, otherwise BUG email will be sent to the old address.

This PR simplifies this by letting BUGHST default to 0, and change the code in RXPBUG to check for 0 and treat it in the same way as if it was (one of) the local address(es).

Closes #2331.

2024-09-05 14:29 UTC, eswenson1 commented
Did you intend to assign to me or to have me be a reviewer? If you did intend to assign to me (and Lars) just what are you expecting us to do?

2024-09-05 17:16 UTC, eswenson1 approved these changes

2024-09-06 07:33 UTC, larsbrinkhoff requested changes
Would be approved, except the branch needs rebasing, and bumping file version.

2024-09-06 07:34 UTC, larsbrinkhoff commented
@eswenson1, @bictorv I suggest this and #2337 can be merged in quick succession with only one file version bump.  There's no added value in run-away version numbers.

2024-09-06 07:38 UTC, bictorv commented
Please go ahead with rebasing and version bumping etc? I'm worried I would do something bad - I'm not a git wiz.

2024-09-06 08:45 UTC, larsbrinkhoff approved these changes
Approved; I did the rebasing and bumping.

2024-09-06 11:27 UTC, merged