Let COMSAT recompile .MAIL.;NAMES when HOSTS3 has been updated
PDP-10/its pull request #2337
Opened 2024-09-04 08:41 UTC by bictorv

NAMES is normally recompiled to a binary "EQV file" when either there was no such file, or NAMES has been updated later than the creation date of the EQV file.

However, the compilation translates host names in NAMES to binary host addresses in the EQV file, so if the address of some host name has changed since compilation, the new addresses won't be used.

This PR checks for this case: when NAMES would not normally need recompilation, check if SYSBIN;HOSTS3 has been updated since the last NAMES compilation and if so, recompile to get any fresh host addresses.

All changed code is under a `$$H3CHK` switch.

Closes #2330.

2024-09-05 14:28 UTC, eswenson1 commented
Did you intend to assign to me or to have me be a reviewer? If you did intend to assign to me (and Lars) just what are you expecting us to do?

2024-09-05 17:21 UTC, eswenson1 approved these changes

2024-09-06 07:31 UTC, larsbrinkhoff commented
Looks like @bictorv assigned us by mistake, and then assigned himself.

@eswenson1, you shouldn't approve this if you want file versions to be bumped.

2024-09-06 11:28 UTC, larsbrinkhoff approved these changes

2024-09-06 13:54 UTC, eswenson1 requested changes
Please bump file FN2 versions.

Thanks @larsbrinkhoff

2024-09-06 13:56 UTC, eswenson1 requested changes
Please bump FN2.

2024-09-06 13:57 UTC, bictorv commented
> Please bump FN2.

Lars did already do that? But only once for the two PRs.

2024-09-06 14:02 UTC, eswenson1 commented
Right. It looks like this PR doesn’t have FN2 bumped — unless he merged this PR’s changed into the other PR. I can’t tell.

2024-09-06 14:04 UTC, bictorv commented
You can tell from the FN2 of the changed file. :-)

2024-09-06 14:16 UTC, eswenson1 reviewed
Yes, but this PR still has version 585 and doesn’t get renamed. Did @larsbrinkhoff merge this change into the other PR?

2024-09-06 14:18 UTC, eswenson1 approved these changes
Ah! The other PR did the rename from 584 to 585 and this PR modified 585. So all good to go.

2024-09-07 05:31 UTC, merged

2024-09-07 05:32 UTC, larsbrinkhoff commented
Yes, version was bumped in the very previous pull request.  Merged now.